[package]
name = "nameless-messenger"
version = "0.1.0"
edition = "2024"

[dependencies]
rsa = "0.9"
aes-gcm = "0.10"
rand = "0.8"
hex = "0.4"

[[bin]]
name = "rust_client"
path = "tempworkah/main.rs"